import 'package:flutter/material.dart';

import '../src/colors/colors.dart';

class DepartamentosMunicipiosWidget extends StatefulWidget {
  final String? departamentoSeleccionado;
  final String? municipioSeleccionado;
  final Function(String, String) onSelectionChanged;

  const DepartamentosMunicipiosWidget({
    Key? key,
    required this.departamentoSeleccionado,
    required this.municipioSeleccionado,
    required this.onSelectionChanged,
  }) : super(key: key);

  @override
  _DepartamentosMunicipiosWidgetState createState() => _DepartamentosMunicipiosWidgetState();
}

class _DepartamentosMunicipiosWidgetState extends State<DepartamentosMunicipiosWidget> {
  final Map<String, List<String>> departamentosYMunicipios = {

    'Antioquia': [
      'Abejorral',
      'Abriaquí',
      'Alejandría',
      'Amagá',
      'Amalfi',
      'Andes',
      'Angelópolis',
      'Angostura',
      'Anorí',
      'Anzá',
      'Apartadó',
      'Arboletes',
      'Argelia',
      'Armenia',
      'Barbosa',
      'Bello',
      'Belmira',
      'Betania',
      'Betulia',
      'Briceño',
      'Buriticá',
      'Cáceres',
      'Caicedo',
      'Caldas',
      'Campamento',
      'Cañasgordas',
      'Caracolí',
      'Caramanta',
      'Carepa',
      'Carolina del Príncipe',
      'Caucasia',
      'Chigorodó',
      'Cisneros',
      'Ciudad Bolívar',
      'Cocorná',
      'Concepción',
      'Concordia',
      'Copacabana',
      'Dabeiba',
      'Donmatías',
      'Ebéjico',
      'El Bagre',
      'El Carmen de Viboral',
      'El Peñol',
      'El Retiro',
      'El Santuario',
      'Entrerríos',
      'Envigado',
      'Fredonia',
      'Frontino',
      'Giraldo',
      'Girardota',
      'Gómez Plata',
      'Granada',
      'Guadalupe',
      'Guarne',
      'Guatapé',
      'Heliconia',
      'Hispania',
      'Itagüí',
      'Ituango',
      'Jardín',
      'Jericó',
      'La Ceja',
      'La Estrella',
      'La Pintada',
      'La Unión',
      'Liborina',
      'Maceo',
      'Marinilla',
      'Medellín',
      'Montebello',
      'Murindó',
      'Mutatá',
      'Nariño',
      'Nechí',
      'Necoclí',
      'Olaya',
      'Peque',
      'Pueblorrico',
      'Puerto Berrío',
      'Puerto Nare',
      'Puerto Triunfo',
      'Remedios',
      'Rionegro',
      'Sabanalarga',
      'Sabaneta',
      'Salgar',
      'San Andrés de Cuerquía',
      'San Carlos',
      'San Francisco',
      'San Jerónimo',
      'San José de la Montaña',
      'San Juan de Urabá',
      'San Luis',
      'San Pedro de los Milagros',
      'San Pedro de Urabá',
      'San Rafael',
      'San Roque',
      'San Vicente',
      'Santa Bárbara',
      'Santa Fe de Antioquia',
      'Santa Rosa de Osos',
      'Santo Domingo',
      'Segovia',
      'Sonsón',
      'Sopetrán',
      'Támesis',
      'Tarazá',
      'Tarso',
      'Titiribí',
      'Toledo',
      'Turbo',
      'Uramita',
      'Urrao',
      'Valdivia',
      'Valparaíso',
      'Vegachí',
      'Venecia',
      'Vigía del Fuerte',
      'Yalí',
      'Yarumal',
      'Yolombó',
      'Yondó',
      'Zaragoza'
    ],

    'Amazonas': [
      'Leticia',
      'Puerto Nariño',
      'El Encanto',
      'La Chorrera',
      'La Pedrera',
      'La Victoria',
      'Miriti - Paraná',
      'Puerto Alegría',
      'Puerto Arica',
      'Puerto Santander',
      'Tarapacá'
    ],

    'Arauca': [
      'Arauca',
      'Arauquita',
      'Cravo Norte',
      'Fortul',
      'Puerto Rondón',
      'Saravena',
      'Tame'
    ],

    'Atlántico': [
      'Barranquilla',
      'Baranoa',
      'Campo de la Cruz',
      'Candelaria',
      'Galapa',
      'Juan de Acosta',
      'Luruaco',
      'Malambo',
      'Manatí',
      'Palmar de Varela',
      'Piojó',
      'Polonuevo',
      'Ponedera',
      'Puerto Colombia',
      'Repelón',
      'Sabanagrande',
      'Sabanalarga',
      'Santa Lucía',
      'Santo Tomás',
      'Soledad',
      'Suán',
      'Tubará',
      'Usiacurí'
    ],

    'Bolívar': [
      'Achí',
      'Altos del Rosario',
      'Arenal',
      'Arjona',
      'Arroyohondo',
      'Barranco de Loba',
      'Calamar',
      'Cantagallo',
      'Cartagena',
      'Cicuco',
      'Clemencia',
      'Córdoba',
      'El Carmen de Bolívar',
      'El Guamo',
      'El Peñón',
      'Hatillo de Loba',
      'Magangué',
      'Mahates',
      'Margarita',
      'María la Baja',
      'Mompós',
      'Montecristo',
      'Morales',
      'Norosí',
      'Pinillos',
      'Regidor',
      'Río Viejo',
      'San Cristóbal',
      'San Estanislao',
      'San Fernando',
      'San Jacinto',
      'San Jacinto del Cauca',
      'San Juan Nepomuceno',
      'San Martín de Loba',
      'Santa Catalina',
      'Santa Rosa',
      'Santa Rosa del Sur',
      'Simití',
      'Soplaviento',
      'Talaigua Nuevo',
      'Tiquisio',
      'Turbaco',
      'Turbaná',
      'Villanueva',
      'Zambrano'
    ],

    'Boyacá': [
      'Almeida',
      'Aquitania',
      'Arcabuco',
      'Belén',
      'Berbeo',
      'Betéitiva',
      'Boavita',
      'Boyacá',
      'Briceño',
      'Buenavista',
      'Busbanzá',
      'Caldas',
      'Campohermoso',
      'Cerinza',
      'Chinavita',
      'Chiquinquirá',
      'Chiscas',
      'Chita',
      'Chitaraque',
      'Chivatá',
      'Chivor',
      'Ciénega',
      'Cómbita',
      'Coper',
      'Corrales',
      'Covarachía',
      'Cubará',
      'Cucaita',
      'Cuitiva',
      'Duitama',
      'El Cocuy',
      'El Espino',
      'Firavitoba',
      'Floresta',
      'Gachantivá',
      'Gámeza',
      'Garagoa',
      'Guacamayas',
      'Guateque',
      'Guayatá',
      'Güicán',
      'Iza',
      'Jenesano',
      'Jericó',
      'La Capilla',
      'La Uvita',
      'La Victoria',
      'Labranzagrande',
      'Macanal',
      'Maripí',
      'Miraflores',
      'Mongua',
      'Monguí',
      'Moniquirá',
      'Motavita',
      'Muzo',
      'Nobsa',
      'Nuevo Colón',
      'Oicatá',
      'Otanche',
      'Pachavita',
      'Páez',
      'Paipa',
      'Pajarito',
      'Panqueba',
      'Pauna',
      'Paya',
      'Paz de Río',
      'Pesca',
      'Pisba',
      'Puerto Boyacá',
      'Quípama',
      'Ramiriquí',
      'Ráquira',
      'Rondón',
      'Saboyá',
      'Sáchica',
      'Samacá',
      'San Eduardo',
      'San José de Pare',
      'San Luis de Gaceno',
      'San Mateo',
      'San Miguel de Sema',
      'San Pablo de Borbur',
      'Santa María',
      'Santa Rosa de Viterbo',
      'Santa Sofía',
      'Santana',
      'Sativanorte',
      'Sativasur',
      'Siachoque',
      'Soatá',
      'Socha',
      'Socotá',
      'Sogamoso',
      'Somondoco',
      'Sora',
      'Soracá',
      'Sotaquirá',
      'Susacón',
      'Sutamarchán',
      'Sutatenza',
      'Tasco',
      'Tenza',
      'Tibaná',
      'Tibasosa',
      'Tinjacá',
      'Tipacoque',
      'Toca',
      'Togüí',
      'Tópaga',
      'Tota',
      'Tunja',
      'Tununguá',
      'Turmequé',
      'Tuta',
      'Tutazá',
      'Úmbita',
      'Ventaquemada',
      'Villa de Leyva',
      'Viracachá',
      'Zetaquira'
    ],
    'Caldas': [
      'Aguadas',
      'Anserma',
      'Aranzazu',
      'Belalcázar',
      'Chinchiná',
      'Filadelfia',
      'La Dorada',
      'La Merced',
      'Manizales',
      'Manzanares',
      'Marmato',
      'Marquetalia',
      'Marulanda',
      'Neira',
      'Norcasia',
      'Pácora',
      'Palestina',
      'Pensilvania',
      'Riosucio',
      'Risaralda',
      'Salamina',
      'Samaná',
      'San José',
      'Supía',
      'Victoria',
      'Villamaría',
      'Viterbo'
    ],
    'Caquetá': [
      'Albania',
      'Belén de los Andaquíes',
      'Cartagena del Chairá',
      'Curillo',
      'El Doncello',
      'El Paujil',
      'Florencia',
      'La Montañita',
      'Milán',
      'Morelia',
      'Puerto Rico',
      'San José del Fragua',
      'San Vicente del Caguán',
      'Solano',
      'Solita',
      'Valparaíso'
    ],
    'Casanare': [
      'Aguazul',
      'Chámeza',
      'Hato Corozal',
      'La Salina',
      'Maní',
      'Monterrey',
      'Nunchía',
      'Orocué',
      'Paz de Ariporo',
      'Pore',
      'Recetor',
      'Sabanalarga',
      'Sácama',
      'San Luis de Palenque',
      'Támara',
      'Tauramena',
      'Trinidad',
      'Villanueva',
      'Yopal'
    ],
    'Cauca': [
      'Almaguer',
      'Argelia',
      'Balboa',
      'Bolívar',
      'Buenos Aires',
      'Cajibío',
      'Caldono',
      'Caloto',
      'Corinto',
      'El Tambo',
      'Florencia',
      'Guachené',
      'Guapí',
      'Inzá',
      'Jambaló',
      'La Sierra',
      'La Vega',
      'López',
      'Mercaderes',
      'Miranda',
      'Morales',
      'Padilla',
      'Páez',
      'Patía',
      'Piamonte',
      'Piendamó',
      'Popayán',
      'Puerto Tejada',
      'Puracé',
      'Rosas',
      'San Sebastián',
      'Santa Rosa',
      'Santander de Quilichao',
      'Silvia',
      'Sotará',
      'Suárez',
      'Sucre',
      'Timbío',
      'Timbiquí',
      'Toribío',
      'Totoró',
      'Villa Rica'
    ],
    'Cesar': [
      'Aguachica',
      'Agustín Codazzi',
      'Astrea',
      'Becerril',
      'Bosconia',
      'Chimichagua',
      'Chiriguaná',
      'Curumaní',
      'El Copey',
      'El Paso',
      'Gamarra',
      'González',
      'La Gloria',
      'La Jagua de Ibirico',
      'La Paz',
      'Manaure Balcón del Cesar',
      'Pailitas',
      'Pelaya',
      'Pueblo Bello',
      'Río de Oro',
      'San Alberto',
      'San Diego',
      'San Martín',
      'Tamalameque',
      'Valledupar'
    ],
    'Chocó': [
      'Acandí',
      'Alto Baudó',
      'Atrato',
      'Bagadó',
      'Bahía Solano',
      'Bajo Baudó',
      'Bojayá',
      'Cértegui',
      'Condoto',
      'El Cantón del San Pablo',
      'El Carmen de Atrato',
      'El Litoral del San Juan',
      'Istmina',
      'Juradó',
      'Lloró',
      'Medio Atrato',
      'Medio Baudó',
      'Medio San Juan',
      'Nóvita',
      'Nuquí',
      'Quibdó',
      'Río Iró',
      'Río Quito',
      'Riosucio',
      'San José del Palmar',
      'Sipí',
      'Tadó',
      'Unguía',
      'Unión Panamericana'
    ],
    'Córdoba': [
      'Ayapel',
      'Buenavista',
      'Canalete',
      'Cereté',
      'Chimá',
      'Chinú',
      'Ciénaga de Oro',
      'Cotorra',
      'La Apartada',
      'Lorica',
      'Los Córdobas',
      'Momil',
      'Montelíbano',
      'Montería',
      'Moñitos',
      'Planeta Rica',
      'Pueblo Nuevo',
      'Puerto Escondido',
      'Puerto Libertador',
      'Purísima',
      'Sahagún',
      'San Andrés de Sotavento',
      'San Antero',
      'San Bernardo del Viento',
      'San Carlos',
      'San José de Uré',
      'San Pelayo',
      'Tierralta',
      'Tuchín',
      'Valencia'
    ],
    'Cundinamarca': [
      'Agua de Dios',
      'Albán',
      'Anapoima',
      'Anolaima',
      'Apulo',
      'Arbeláez',
      'Beltrán',
      'Bituima',
      'Bojacá',
      'Cabrera',
      'Cachipay',
      'Cajicá',
      'Caparrapí',
      'Cáqueza',
      'Carmen de Carupa',
      'Chaguaní',
      'Chía',
      'Chipaque',
      'Choachí',
      'Chocontá',
      'Cogua',
      'Cota',
      'Cucunubá',
      'El Colegio',
      'El Peñón',
      'El Rosal',
      'Facatativá',
      'Fómeque',
      'Fosca',
      'Funza',
      'Fúquene',
      'Fusagasugá',
      'Gachalá',
      'Gachancipá',
      'Gachetá',
      'Gama',
      'Girardot',
      'Granada',
      'Guachetá',
      'Guaduas',
      'Guasca',
      'Guataquí',
      'Guatavita',
      'Guayabal de Síquima',
      'Guayabetal',
      'Gutiérrez',
      'Jerusalén',
      'Junín',
      'La Calera',
      'La Mesa',
      'La Palma',
      'La Peña',
      'La Vega',
      'Lenguazaque',
      'Machetá',
      'Madrid',
      'Manta',
      'Medina',
      'Mosquera',
      'Nariño',
      'Nemocón',
      'Nilo',
      'Nimaima',
      'Nocaima',
      'Venecia (Ospina Pérez)',
      'Pacho',
      'Paime',
      'Pandi',
      'Paratebueno',
      'Pasca',
      'Puerto Salgar',
      'Pulí',
      'Quebradanegra',
      'Quetame',
      'Quipile',
      'Ricaurte',
      'San Antonio del Tequendama',
      'San Bernardo',
      'San Cayetano',
      'San Francisco',
      'San Juan de Río Seco',
      'Sasaima',
      'Sesquilé',
      'Sibaté',
      'Silvania',
      'Simijaca',
      'Soacha',
      'Sopo',
      'Subachoque',
      'Suesca',
      'Supatá',
      'Susa',
      'Sutatausa',
      'Tabio',
      'Tausa',
      'Tena',
      'Tenjo',
      'Tibacuy',
      'Tibirita',
      'Tocaima',
      'Tocancipá',
      'Topaipí',
      'Ubalá',
      'Ubaque',
      'Ubaté',
      'Une',
      'Útica',
      'Vergara',
      'Vianí',
      'Villagómez',
      'Villapinzón',
      'Villeta',
      'Viotá',
      'Yacopí',
      'Zipacón',
      'Zipaquirá'
    ],
    'Guainía': [
      'Barranco Minas',
      'Cacahual',
      'Inírida',
      'La Guadalupe',
      'Mapiripana',
      'Morichal',
      'Pana Pana',
      'Puerto Colombia',
      'San Felipe'
    ],
    'Guaviare': [
      'Calamar',
      'El Retorno',
      'Miraflores',
      'San José del Guaviare'
    ],
    'Huila': [
      'Acevedo',
      'Agrado',
      'Aipe',
      'Algeciras',
      'Altamira',
      'Baraya',
      'Campoalegre',
      'Colombia',
      'Elías',
      'Garzón',
      'Gigante',
      'Guadalupe',
      'Hobo',
      'Iquira',
      'Isnos',
      'La Argentina',
      'La Plata',
      'Nátaga',
      'Neiva',
      'Oporapa',
      'Paicol',
      'Palermo',
      'Palestina',
      'Pital',
      'Pitalito',
      'Rivera',
      'Saladoblanco',
      'San Agustín',
      'Santa María',
      'Suaza',
      'Tarqui',
      'Tello',
      'Teruel',
      'Tesalia',
      'Timaná',
      'Villavieja',
      'Yaguará'
    ],
    'La Guajira': [
      'Albania',
      'Barrancas',
      'Dibulla',
      'Distracción',
      'El Molino',
      'Fonseca',
      'Hatonuevo',
      'La Jagua del Pilar',
      'Maicao',
      'Manaure',
      'Riohacha',
      'San Juan del Cesar',
      'Uribia',
      'Urumita',
      'Villanueva'
    ],
    'Magdalena': [
      'Algarrobo',
      'Aracataca',
      'Ariguaní',
      'Cerro de San Antonio',
      'Chibolo',
      'Ciénaga',
      'Concordia',
      'El Banco',
      'El Piñón',
      'El Retén',
      'Fundación',
      'Guamal',
      'Nueva Granada',
      'Pedraza',
      'Pivijay',
      'Plato',
      'Puebloviejo',
      'Remolino',
      'Sabanas de San Ángel',
      'Salamina',
      'San Sebastián de Buenavista',
      'San Zenón',
      'Santa Ana',
      'Santa Bárbara de Pinto',
      'Santa Marta',
      'Sitionuevo',
      'Tenerife',
      'Zapayán',
      'Zona Bananera'
    ],
    'Meta': [
      'Acacías',
      'Barranca de Upía',
      'Cabuyaro',
      'Castilla la Nueva',
      'Cubarral',
      'Cumaral',
      'El Calvario',
      'El Castillo',
      'El Dorado',
      'Fuente de Oro',
      'Granada',
      'Guamal',
      'La Macarena',
      'Lejanías',
      'Mapiripán',
      'Mesetas',
      'Puerto Concordia',
      'Puerto Gaitán',
      'Puerto Lleras',
      'Puerto López',
      'Puerto Rico',
      'Restrepo',
      'San Carlos de Guaroa',
      'San Juan de Arama',
      'San Juanito',
      'San Martín',
      'Uribe',
      'Villavicencio',
      'Vista Hermosa'
    ],
    'Nariño': [
      'Aldana',
      'Ancuya',
      'Arboleda',
      'Barbacoas',
      'Belén',
      'Buesaco',
      'Chachagüí',
      'Colón',
      'Consacá',
      'Contadero',
      'Córdoba',
      'Cuaspud',
      'Cumbal',
      'Cumbitara',
      'El Charco',
      'El Peñol',
      'El Rosario',
      'El Tablón de Gómez',
      'El Tambo',
      'Francisco Pizarro',
      'Funes',
      'Guachucal',
      'Guaitarilla',
      'Gualmatán',
      'Iles',
      'Imués',
      'Ipiales',
      'La Cruz',
      'La Florida',
      'La Llanada',
      'La Tola',
      'La Unión',
      'Leiva',
      'Linares',
      'Los Andes',
      'Magüí Payán',
      'Mallama',
      'Mosquera',
      'Nariño',
      'Olaya Herrera',
      'Ospina',
      'Pasto',
      'Policarpa',
      'Potosí',
      'Providencia',
      'Puerres',
      'Pupiales',
      'Ricaurte',
      'Roberto Payán',
      'Samaniego',
      'San Andrés de Tumaco',
      'San Bernardo',
      'San Lorenzo',
      'San Pablo',
      'San Pedro de Cartago',
      'Sandoná',
      'Santa Bárbara',
      'Santacruz',
      'Sapuyes',
      'Taminango',
      'Tangua',
      'Túquerres',
      'Yacuanquer'
    ],
    'Norte de Santander': [
      'Abrego',
      'Arboledas',
      'Bochalema',
      'Bucarasica',
      'Cáchira',
      'Cácota',
      'Chinácota',
      'Chitagá',
      'Convención',
      'Cúcuta',
      'Cucutilla',
      'Durania',
      'El Carmen',
      'El Tarra',
      'El Zulia',
      'Gramalote',
      'Hacarí',
      'Herrán',
      'La Esperanza',
      'La Playa',
      'Labateca',
      'Los Patios',
      'Lourdes',
      'Mutiscua',
      'Ocaña',
      'Pamplona',
      'Pamplonita',
      'Puerto Santander',
      'Ragonvalia',
      'Salazar',
      'San Calixto',
      'San Cayetano',
      'Santiago',
      'Sardinata',
      'Silos',
      'Teorama',
      'Tibú',
      'Toledo',
      'Villa Caro',
      'Villa del Rosario'
    ],
    'Putumayo': [
      'Colón',
      'Mocoa',
      'Orito',
      'Puerto Asís',
      'Puerto Caicedo',
      'Puerto Guzmán',
      'Leguízamo',
      'San Francisco',
      'San Miguel',
      'Santiago',
      'Sibundoy',
      'Valle del Guamuez',
      'Villagarzón'
    ],
    'Quindío': [
      'Armenia',
      'Buenavista',
      'Calarcá',
      'Circasia',
      'Córdoba',
      'Filandia',
      'Génova',
      'La Tebaida',
      'Montenegro',
      'Pijao',
      'Quimbaya',
      'Salento'
    ],
    'Risaralda': [
      'Apía',
      'Balboa',
      'Belén de Umbría',
      'Dosquebradas',
      'Guática',
      'La Celia',
      'La Virginia',
      'Marsella',
      'Mistrató',
      'Pereira',
      'Pueblo Rico',
      'Quinchía',
      'Santa Rosa de Cabal',
      'Santuario'
    ],
    'San Andrés y Providencia': [
      'San Andrés',
      'Providencia'
    ],
    'Santander': [
      'Aguada',
      'Albania',
      'Aratoca',
      'Barbosa',
      'Barichara',
      'Barrancabermeja',
      'Betulia',
      'Bolívar',
      'Bucaramanga',
      'Cabrera',
      'California',
      'Capitanejo',
      'Carcasí',
      'Cepitá',
      'Cerrito',
      'Charalá',
      'Charta',
      'Chima',
      'Chipatá',
      'Cimitarra',
      'Concepción',
      'Confines',
      'Contratación',
      'Coromoro',
      'Curití',
      'El Carmen de Chucurí',
      'El Guacamayo',
      'El Peñón',
      'El Playón',
      'Encino',
      'Enciso',
      'Florián',
      'Floridablanca',
      'Galán',
      'Gámbita',
      'Girón',
      'Guaca',
      'Guadalupe',
      'Guapotá',
      'Guavatá',
      'Güepsa',
      'Hato',
      'Jesús María',
      'Jordán',
      'La Belleza',
      'La Paz',
      'Landázuri',
      'Lebríja',
      'Los Santos',
      'Macaravita',
      'Málaga',
      'Matanza',
      'Mogotes',
      'Molagavita',
      'Ocamonte',
      'Oiba',
      'Onzaga',
      'Palmar',
      'Palmas del Socorro',
      'Páramo',
      'Piedecuesta',
      'Pinchote',
      'Puente Nacional',
      'Puerto Parra',
      'Puerto Wilches',
      'Rionegro',
      'Sabana de Torres',
      'San Andrés',
      'San Benito',
      'San Gil',
      'San Joaquín',
      'San José de Miranda',
      'San Miguel',
      'San Vicente de Chucurí',
      'Santa Bárbara',
      'Santa Helena del Opón',
      'Simacota',
      'Socorro',
      'Suaita',
      'Sucre',
      'Suratá',
      'Tona',
      'Valle de San José',
      'Vélez',
      'Vetas',
      'Villanueva',
      'Zapatoca'
    ],
    'Sucre': [
      'Buenavista',
      'Caimito',
      'Chalán',
      'Colosó',
      'Corozal',
      'Coveñas',
      'El Roble',
      'Galeras',
      'Guaranda',
      'La Unión',
      'Los Palmitos',
      'Majagual',
      'Morroa',
      'Ovejas',
      'Palmito',
      'Sampués',
      'San Benito Abad',
      'San Juan de Betulia',
      'San Marcos',
      'San Onofre',
      'San Pedro',
      'Santiago de Tolú',
      'Since',
      'Sincelejo',
      'Tolú Viejo'
    ],
    'Tolima': [
      'Alpujarra',
      'Alvarado',
      'Ambalema',
      'Anzoátegui',
      'Armero',
      'Ataco',
      'Cajamarca',
      'Carmen de Apicalá',
      'Casabianca',
      'Chaparral',
      'Coello',
      'Coyaima',
      'Cunday',
      'Dolores',
      'Espinal',
      'Falan',
      'Flandes',
      'Fresno',
      'Guamo',
      'Herveo',
      'Honda',
      'Ibagué',
      'Icononzo',
      'Lérida',
      'Líbano',
      'Mariquita',
      'Melgar',
      'Murillo',
      'Natagaima',
      'Ortega',
      'Palocabildo',
      'Piedras',
      'Planadas',
      'Prado',
      'Purificación',
      'Rioblanco',
      'Roncesvalles',
      'Rovira',
      'Saldaña',
      'San Antonio',
      'San Luis',
      'Santa Isabel',
      'Suárez',
      'Valle de San Juan',
      'Venadillo',
      'Villahermosa',
      'Villarrica'
    ],
    'Valle del Cauca': [
      'Alcalá',
      'Andalucía',
      'Ansermanuevo',
      'Argelia',
      'Bolívar',
      'Buenaventura',
      'Buga',
      'Bugalagrande',
      'Caicedonia',
      'Cali',
      'Calima',
      'Candelaria',
      'Cartago',
      'Dagua',
      'El Águila',
      'El Cairo',
      'El Cerrito',
      'El Dovio',
      'Florida',
      'Ginebra',
      'Guacarí',
      'Jamundí',
      'La Cumbre',
      'La Unión',
      'La Victoria',
      'Obando',
      'Palmira',
      'Pradera',
      'Restrepo',
      'Riofrío',
      'Roldanillo',
      'San Pedro',
      'Sevilla',
      'Toro',
      'Trujillo',
      'Tuluá',
      'Ulloa',
      'Versalles',
      'Vijes',
      'Yotoco',
      'Yumbo',
      'Zarzal'
    ],
    'Vaupés': [
      'Carurú',
      'Mitú',
      'Taraira',
      'Papunahua',
      'Yavaraté'
    ],
    'Vichada': [
      'Cumaribo',
      'La Primavera',
      'Puerto Carreño',
      'Santa Rosalía'
    ],
    'Bogotá D.C.': [
      'Bogotá'
    ],
  };

  String? departamentoSeleccionado;
  String? municipioSeleccionado;
  List<String> municipiosDisponibles = [];

  @override
  void initState() {
    super.initState();
    departamentoSeleccionado = widget.departamentoSeleccionado;
    municipioSeleccionado = widget.municipioSeleccionado;

    // ✅ Asegurar que el departamento seleccionado exista en la lista
    if (departamentoSeleccionado != null &&
        !departamentosYMunicipios.keys.contains(departamentoSeleccionado)) {
      departamentoSeleccionado = null; // 🔥 Resetear si no existe
    }

    if (departamentoSeleccionado != null) {
      municipiosDisponibles = departamentosYMunicipios[departamentoSeleccionado!] ?? [];
    }

    // ✅ Asegurar que el municipio seleccionado exista en la lista
    if (municipioSeleccionado != null && !municipiosDisponibles.contains(municipioSeleccionado)) {
      municipioSeleccionado = null; // 🔥 Resetear si no existe
    }
  }

  void _actualizarMunicipios(String departamento) {
    setState(() {
      departamentoSeleccionado = departamento;
      municipiosDisponibles = departamentosYMunicipios[departamento] ?? [];
      municipioSeleccionado = null;
    });

    widget.onSelectionChanged(departamento, "");
  }

  void _actualizarMunicipio(String municipio) {
    setState(() {
      municipioSeleccionado = municipio;
    });

    widget.onSelectionChanged(departamentoSeleccionado!, municipio);
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        _buildDropdownContainer(
          title: "Departamento",
          child: DropdownButtonFormField<String>(
            dropdownColor: blanco,
            isExpanded: true,
            value: departamentoSeleccionado, // ✅ Ahora está validado
            hint: const Text("Seleccione un departamento"),
            decoration: _inputDecoration(),
            items: departamentosYMunicipios.keys.map((String departamento) {
              return DropdownMenuItem<String>(
                value: departamento,
                child: Text(departamento),
              );
            }).toList(),
            onChanged: (String? nuevoDepartamento) {
              if (nuevoDepartamento != null) {
                _actualizarMunicipios(nuevoDepartamento);
              }
            },
          ),
        ),

        const SizedBox(height: 20),

        _buildDropdownContainer(
          title: "Municipio",
          child: DropdownButtonFormField<String>(
            dropdownColor: blanco,
            isExpanded: true,
            value: municipioSeleccionado, // ✅ Ahora está validado
            hint: const Text("Seleccione un municipio"),
            decoration: _inputDecoration(),
            items: municipiosDisponibles.map((String municipio) {
              return DropdownMenuItem<String>(
                value: municipio,
                child: Text(municipio),
              );
            }).toList(),
            onChanged: (String? nuevoMunicipio) {
              if (nuevoMunicipio != null) {
                _actualizarMunicipio(nuevoMunicipio);
              }
            },
          ),
        ),
      ],
    );
  }

  Widget _buildDropdownContainer({required String title, required Widget child}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(title, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
        const SizedBox(height: 5),
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
          decoration: BoxDecoration(
            border: Border.all(color: Colors.grey),
            borderRadius: BorderRadius.circular(10),
          ),
          child: child,
        ),
      ],
    );
  }

  InputDecoration _inputDecoration() {
    return const InputDecoration(
      border: InputBorder.none,
      contentPadding: EdgeInsets.symmetric(horizontal: 10, vertical: 5),
    );
  }
}
