// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTKLwjpQ_JqVkTyMdCWj1MtKRGQJV0Nd8',
    appId: '1:438491594577:web:d2c78e5173d947d7375d70',
    messagingSenderId: '438491594577',
    projectId: 'tu-proceso-ya-fe845',
    authDomain: 'tu-proceso-ya-fe845.firebaseapp.com',
    storageBucket: 'tu-proceso-ya-fe845.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB83Rrkj4XEZtLXIn49jtfJBs2KthNtrb8',
    appId: '1:438491594577:android:9634a409460efb5e375d70',
    messagingSenderId: '438491594577',
    projectId: 'tu-proceso-ya-fe845',
    storageBucket: 'tu-proceso-ya-fe845.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8c3GzDjKj9L0WZr2DBPf6RcBu7LZc870',
    appId: '1:438491594577:ios:b004fa29eb3f68f3375d70',
    messagingSenderId: '438491594577',
    projectId: 'tu-proceso-ya-fe845',
    storageBucket: 'tu-proceso-ya-fe845.firebasestorage.app',
    iosBundleId: 'com.example.tuprocesoya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8c3GzDjKj9L0WZr2DBPf6RcBu7LZc870',
    appId: '1:438491594577:ios:b004fa29eb3f68f3375d70',
    messagingSenderId: '438491594577',
    projectId: 'tu-proceso-ya-fe845',
    storageBucket: 'tu-proceso-ya-fe845.firebasestorage.app',
    iosBundleId: 'com.example.tuprocesoya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTKLwjpQ_JqVkTyMdCWj1MtKRGQJV0Nd8',
    appId: '1:438491594577:web:4ae0ff62abaa57b0375d70',
    messagingSenderId: '438491594577',
    projectId: 'tu-proceso-ya-fe845',
    authDomain: 'tu-proceso-ya-fe845.firebaseapp.com',
    storageBucket: 'tu-proceso-ya-fe845.firebasestorage.app',
  );
}
